### ISSUE TITLE
Einheiten auf einer Map darstellen

### ISSUE THREAD

**Issue by 9chris2toph** [christophhense/OpenTacticalDispatcher#3]
Moin,

wäre es vielleicht möglich, sofern ich es richtig gesehen habe ist die Grundlage ja bereits vorhanden,
die Einheiten auf einer Karte darzustellen? 
ZBsp Google Maps oder einer Open Source Variante?

Das würde die Welt deutlich vereinfachen und wäre so unfassbar hilfreich.

Damit vielleicht auch verknüpft Einsätze auf der Karte darstellen?
Wo welche Örtlichkeiten sind? 

Das wäre für größere Veranstaltungen einfach der ultimative Hit!

**Comment by christophhense** [comment]
Moin,
habe ich im Anschluss an das benutzerdefinierte Dashboard geplant. Vor 2025 ist aber nicht damit zu rechnen.
